### PR TITLE
Patch 

### LINKED ISSUE #11: Bugs!
hello, i'm playing version 1.4.4 and i noticed some bugs:
1st: Result Logistic Pipe does not save the id after you click the save button.
2nd: the Crafting Manager Pipe has a buggy HUD, the items in the player's inventory are invisible and the buttons that configure the pipe are missing.
Screenshot_1

### PR DESCRIPTION
**Pull request by KorewaLidesu**
Fix #11 @Domaman202

### CODE REVIEW

**Comment by KorewaLidesu** [comment]
I recommend rework for external ID system instead so it won't interference with LP ID handler

**Comment by KorewaLidesu** [comment]
@Domaman202

**Comment by KorewaLidesu** [comment]
Add new string for easy translation, fix issue where Package won't show item inside package and Satellite ID.

**Comment by KorewaLidesu** [comment]
Correct changelog

**Comment by KorewaLidesu** [comment]
Small Improves.

**Comment by KorewaLidesu** [comment]
My discord is `azusa#1705` if you want to contact.

**Comment by KorewaLidesu** [comment]
Now introduce new system: ~~copyrighted~~ GUI for SatelliteBus!!!

**Comment by Domaman202** [comment]
VERY VERY VERY BIG THX!))))))

**Pull request merged**
